# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.6

env:
  - DB=MYSQL CORE_RELEASE=3.6

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover realme/tests/
  - bash <(curl -s https://codecov.io/bash) -f coverage.clover -R realme/
